Add gen-install-config script, updated examples

diff --git a/bare-metal/tools/get-ocp-baremetal-install b/bare-metal/tools/get-ocp-baremetal-install
--- a/bare-metal/tools/get-ocp-baremetal-install
+++ b/bare-metal/tools/get-ocp-baremetal-install
@@ -2,7 +2,7 @@
 
 # Pre-reqs:
 #
-# - OCP 4 pull secret in $HOME/.secrets/ocp4-install-pull-secret.txt
+# - OCP 4 pull secret in $HOME/.secrets/ocp4-pull-secret.txt
 
 version=${1:-latest-4.6}
 dest_dir=${2:-./bin}
@@ -11,7 +11,12 @@ me=$(basename $0)
 dest_dir=$(readlink -f $dest_dir)
 
 cmd="openshift-baremetal-install"
-pullsecret_file=$HOME/.secrets/ocp4-install-pull-secret.txt
+pullsecret_file=$HOME/.secrets/ocp4-pull-secret.txt
+
+if [[ ! -d $pull_scret_file ]]; then
+   >&2 echo "Error: Pull secret file not found: $pullsecret_file."
+   exit 5
+fi
 
 extract_dir=$(mktemp -td $me.XXXXXXXXXX)
 cd $extract_dir
